volumes:
  db:

services:
  mailonapi:
    image: mailonapi:latest
    container_name: mailonapi
    restart: always
    depends_on:
      - mailonapi-db
    ports:
      - "6780:8080"
      - "1143:1143"

  mailonapi-db:
    image: mysql:latest
    container_name: mailonapi-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Pu#rari4
    ports:
      - "3308:3306"
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql