export default Object.freeze({
    NOT_AUTHENTICATED: Symbol('NOT_AUTHENTICATED'),
    AUTHENTICATED: Symbol('AUTHENTICATED'),
    AUTHENTICATING_PLAIN: Symbol('AUTHENTICATING_PLAIN'),
    SELECTED: Symbol('SELECTED'),
    SELECTED_READONLY: Symbol('SELECTED_READONLY')
});